version: "3.5"

services:
  db:
    container_name: mysql_db
    image: mysql:8.0.0
    command: --sql_mode=''
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=teste
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - "3307:3306"
    networks:
      - nt-api-template
    volumes:
      - "./script.sql:/docker-entrypoint-initdb.d/1.sql"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
    networks:
      - nt-api-template
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.enabled: "true"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    networks:
      - nt-api-template
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  api: 
    container_name: container-app
    image: img-api
    ports:
      - "8080:80"
    build: 
      context: .
    depends_on:
      - db
      - elasticsearch
    networks:
      - nt-api-template
    environment:
      - ASPNETCORE_URLS=http://*:80
      - ASPNETCORE_ENVIRONMENT=Production

networks:
  nt-api-template:
    driver: bridge
